AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for demo_lambda

Globals:
  Function:
    Timeout: 3

Resources:
  DemoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /src
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.8-v1
