AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for demo_lambda

Globals:
  Function:
    Timeout: 3

Resources:
  DemoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /demo-lambda
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.8-v1

Outputs:  # Required when you use `sam deploy`. Gives information to run lambda via API Gateway
  DemoLambdaApi:
    Description: "API Gateway endpoint URL for Staging environment for Demo Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/demo-lambda"
  DemoLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DemoLambdaFunction.Arn
  DemoLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Demo Lambda function"
    Value: !GetAtt DemoLambdaFunctionRole.Arn