version: 2.1
jobs:
  build-and-test:
    docker:
      - image: demo_lambda:0.3
    steps:
      - checkout
      - setup_remote_docker:
            version: 20.10.2
            docker_layer_caching: true
            reusable: true
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: Docker build and run pytests
          command: |
            TAG=0.1.${CIRCLE_BUILD_NUM}
            echo "circle env var ${REPO_NAME}"
            docker build -t "${REPO_NAME}":$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            pwd
            python -m pytest -xsv test_cake.py

workflows:
  main:
    jobs:
      - build-and-test