version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
      name: Build docker image
      command: |
        docker build -t "${CIRCLE_PROJECT_REPONAME}" .
      - run:
      name: Run unit tests
      command: |
        pwd
        python -m pytest -xsv test_cake.py

workflows:
  main:
    jobs:
      - build-and-test